site_name: Лекции по ИнфоТеху
nav:
  - "Список Лекций": lections.md
  - "Лекции":
    - "Базовое понятие информации": 02.09.2025.md
    - "Свойства информации": 09.09.2025.md
    - "Устройство системы": 13.10.2025.md
    - "Логические операции": 14.10.2025.md
    - "Основы ИБ": 15.09.2025.md
    - "Системы счисления. Особенности округления чисел": 16.09.2025.md
    - "Арифметические и логические основы ЭВМ": 23.09.2025.md
    - "27.10.2025": 27.10.2025.md
    - "Основы сжатия информации. Основы помехоустойчивого кодирования": 30.09.2025.md
  - "Доклады":
    - "Как развернуть свой собственный БПОС-сервер для доступа к Российским сервисам из-за границы?": ru_bpos.md 
    - "Http и Https. Кто круче?": http_https.md
    - "Https наглядно": https_belike.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Sashayerty
    - icon: fontawesome/brands/telegram
      link: https://t.me/Sashayerty
    - icon: fontawesome/brands/vk
      link: https://vk.com/sashayerty
theme:
  features:
    - content.code.copy
    - navigation.sections
    - navigation.footer
    # - navigation.tabs
    # - navigation.tabs.sticky
  icon:
    logo: fontawesome/solid/book-open
  language: ru
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Переключить на светлую тему

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключить на темную тему

    - media: "(prefers-color-scheme: dark)"
      scheme: dracula
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Переключить на системную тему
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - def_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences
